### ISSUE TITLE
Me faltan cosas.

### ISSUE THREAD

**Issue by 104cubes** [CesarLealPerez/CURSOIFCD-0110#1]

**Comment by 104cubes** [comment]
Los links están sin estilos y el fondo no es responsive.
Tampoco consigo ver animación en la oferta..
A lo mejor no estoy viendo el que es.
Tampoco encuentro el layout responsive. El de la imagen "enmedio"

**Comment by CesarLealPerez** [comment]
dejame mirar, pero el ultimo push es de hace 4 dias. a ver si me jodio todo el trabajo y tengo que volver a hacerlo...
